### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by ToshY** [fmonts/ffmpeg-bundle#4]
Update dependency constraints in composer.json to allow Symfony 7

**Comment by fmonts** [comment]
Thank you, I'm on it

**Comment by ToshY** [comment]
Hey @fmonts 👋 

I've just been looking at the dependencies of [PHP-FFMpeg/PHP-FFMpeg](https://github.com/PHP-FFMpeg/PHP-FFMpeg), which seem to be stuck on `^5.4 || ^6.0` as well. PHP-FFmpeg doesn't seem maintained anymore, and I can't find an active fork that is, so I'm not sure what the best approach is 🤔

**Comment by fmonts** [comment]
Yeah, I pushed version 0.8.5 with 7.0 in composer.json, but I'm afraid it won't work... We'll need to fork [PHP-FFMpeg/PHP-FFMpeg](https://github.com/PHP-FFMpeg/PHP-FFMpeg) as well I guess...

**Comment by ToshY** [comment]
Thanks for bumping this already 👍 

I saw there's a PR open in their repo, https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/912, but I'm not sure if it will be merged anytime soon. I've mentioned the maintainer in the hopes it will get some attention.

I'm not in a rush myself to upgrade to Symfony 7, so we could wait a bit and maybe it will get merged in a couple of weeks. Else, like you said, we'd probably need a fork that supports it. If that time comes, I don't mind creating one and publishing it.

**Comment by ToshY** [comment]
Hey @fmonts 👋 

PHP-FFMpeg/PHP-FFMpeg [`v1.2.0`](https://github.com/PHP-FFMpeg/PHP-FFMpeg/releases/tag/v1.2.0) released a couple of hours ago, supporting PHP 8.3 and Symfony 7.

p.s.

Best wishes for the new year.
