### ISSUE TITLE
Autowire doesn't work

### ISSUE THREAD

**Issue by playerro** [fmonts/ffmpeg-bundle#5]
After following instructions in docs I get this error:

Cannot autowire service "App\Controller\Admin\StreamCrudController": argument "$FFProbe" of method "__construct()" references class "FFMpeg\FFProbe" but no such service exists. You should maybe alias this class to the existing "dubture_ffmpeg.ffprobe" service.

Any tips how to autowire FFProbe/FFMpeg?

**Comment by fmonts** [comment]
Yes, you should add this in services.yaml, under `services:`:

`FFMpeg\FFMpeg: '@dubture_ffmpeg.ffmpeg'`

I've updated the readme.
Thank you
